---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: chaos-testing
---
apiVersion: v1
kind: Namespace
metadata:
  name: azure-workload-identity-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: akv-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: fred
