apiVersion: v1
kind: Pod
metadata:
  name: akv-demo
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: "sa-akv-demo"
  containers:
    - image: ghcr.io/azure/azure-workload-identity/msal-go
      name: oidc
      env:
      - name: KEYVAULT_URL
        value: 'https://akv-chaos-demo-meetup.vault.azure.net'
      - name: SECRET_NAME
        value: secret-chaos-demo
  nodeSelector:
    kubernetes.io/os: linux
