---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: "4.6.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h
  upgrade:
    remediation:
      remediateLastFailure: true
  interval: 1m0s
  values:
    # Source: https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
    defaultBackend:
      enabled: true
      nodeSelector:
        kubernetes.azure.com/mode: system
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
          effect: "NoSchedule"

    controller:
      replicaCount: 2
      priorityClassName: system-cluster-critical
      nodeSelector:
        kubernetes.azure.com/mode: system
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
          effect: "NoSchedule"
      admissionWebhooks:
        patch:
          nodeSelector:
            kubernetes.azure.com/mode: system
          tolerations:
            - key: "CriticalAddonsOnly"
              operator: "Exists"
              effect: "NoSchedule"
      metrics:
        enabled: false
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
        type: LoadBalancer
        externalTrafficPolicy: Local
