apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: akv-demo
  annotations:
    azure.workload.identity/client-id: 77248db4-1ed7-43bf-8ceb-f11333cd0e98
  labels:
    azure.workload.identity/use: "true"  # if you're using azure-workload-identity v1.0.0+, this label is not required.
  name: sa-akv-demo
