---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chaos-mesh
spec:
  chart:
    spec:
      chart: chaos-mesh
      version: "2.5.2"
      sourceRef:
        kind: HelmRepository
        name: chaos-mesh
        namespace: flux-system
      interval: 12h
  values:
    # Source: https://github.com/chaos-mesh/chaos-mesh/blob/master/helm/chaos-mesh/values.yaml
    dnsServer:
      create: true
    nodeSelector:
      kubernetes.azure.com/mode: system
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
        effect: "NoSchedule"
    chaosDaemon:
      nodeSelector:
        kubernetes.azure.com/mode: system
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
          effect: "NoSchedule"
    ingress:
      enabled: false
      certManager: false
  interval: 1m
