apiVersion: v1
kind: Pod
metadata:
  name: "fred-test-connection"
  labels:
    app.kubernetes.io/name: fred
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['fred:8080']
  restartPolicy: Never
